### ISSUE TITLE
Ошибка сервера

### ISSUE THREAD

**Issue by Michael-sr** [morpher-ru/uservoice#11]
Здравствуйте!
Перестал работать сервер.
![image](https://user-images.githubusercontent.com/58707036/109835353-f68de400-7c64-11eb-8612-f50cf808ee58.png)

**Comment by bzaar** [comment]
Да, на хостинге проблемы. Разбираемся.

**Comment by bzaar** [comment]
Работоспособность восстановлена.

**Comment by Michael-sr** [comment]
Большое спасибо! Мы, кстати, ваши земляки из Челябинска).
Хотим сказать спасибо за ваши труды и замечательный продукт!

ср, 3 мар. 2021 г. в 23:48, bzaar <notifications@github.com>:

**Comment by bzaar** [comment]
Очень приятно! Спасибо! :)
