### ISSUE TITLE
Добавить кнопки для вставки знаков ударения

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/uservoice#2]
В интерфейс [программы расстановки ударений](https://morpher.ru/accentizer) добавить две экранные кнопки, при нажатии которых в поле ввода в текущую позицию курсора вставляется знак ударения, основного ('\u0301') или побочного  ('\u0300'). Нажатие на кнопку не должно уводить фокус ввода от поля ввода текста. Если фокус находится вне поля ввода, кнопки должны быть disabled.

Кнопки могут выглядеть, например, вот так (обведено зеленым):

![image](https://user-images.githubusercontent.com/4028922/107424707-e37c6e00-6b15-11eb-9009-b5dc41132c77.png)

_По мотивам комментария @Pogrebnoj-Alexandroff: https://github.com/sokirko74/aot/issues/3#issuecomment-760949703_

**Comment by Pogrebnoj-Alexandroff** [comment]
Кроме кода 300 и 301, в интернете, пользователями также используется тег & # 769; устанавливают который после гласной буквы, в слове под ударением. На некоторых продвинутых форумах используется тег [ictus] для выделения буквы под ударением -- сл[ictus]о[/ictus]ва.
