### ISSUE TITLE
Не выполняется запрос к API

### ISSUE THREAD

**Issue by glebalshanskii** [morpher-ru/uservoice#20]
Делаю следующий запрос:

`import requests`
`url = "https://ws3.morpher.ru/russian/declension"`
`params = dict(`
`    s="какая-то строка",`
`    format="json",`
`    token="valid token",`
`)`
`response = requests.get(url=url, params=params)`
`print(response.text)`

Получаю следующую ошику:

`ConnectionResetError: [Errno 54] Connection reset by peer
`

Токен валиный, подписка активна.
Запросы пробовал делать из России и из вне - ошибка одна и та же. Пробовал домены .ru и .me - ошибка повторяется.
Кажется, что API вер-сервиса не работает, нужно починить.

**Comment by bzaar** [comment]
Попробуйте указать заголовок "User-Agent", как показано здесь: https://morpher.ru/ws3/python/

**Comment by glebalshanskii** [comment]
Заработало, спасибо!
