### ISSUE TITLE
Неправильно склоняется «Абрамян Аревик Анушавановна»

### ISSUE THREAD

**Issue by NikaLive** [morpher-ru/uservoice#31]
"Абрамян Аревик Анушавановна" - ФИО женского рода, а программа Морфер распознает и склоняет данное словосочетание как мужской род

**Comment by bzaar** [comment]
Исправлено:

![image](https://github.com/morpher-ru/uservoice/assets/4028922/68eae924-0388-410b-8afd-7df4e4a39b34)

Спасибо большое, что написали!
