### ISSUE TITLE
Периодически не работает API

### ISSUE THREAD

**Issue by rusproject** [morpher-ru/uservoice#4]
Не работает ни один вид запросов, и если открыть ссылку, [например ](https://ws3.morpher.ru/russian/declension?s=%D0%A1%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5%20%D0%BA%D0%BE%D1%80%D0%BE%D0%BB%D0%B5%D0%B2%D1%81%D1%82%D0%B2%D0%BE), в браузере, увидим вот такое сообщение:
![image](https://user-images.githubusercontent.com/62891105/106199964-42152400-61c7-11eb-9325-8b5068d83174.png)

**Comment by bzaar** [comment]
Добрый день! Сейчас работоспособность сервиса восстановлена. Спасибо за ваше сообщение.
