### ISSUE TITLE
Неправильно склоняется «Загери»

### ISSUE THREAD

**Issue by emodaditz** [morpher-ru/uservoice#7]
Загери - Это фамилия. Не должна склоняться

**Comment by bzaar** [comment]
Согласен. Фамилия довольно редкая. Вот несколько профилей ее носителей:

https://www.facebook.com/zageribogdan
https://www.facebook.com/zagerisvet
https://www.instagram.com/_zageri_

@emodaditz, Вы как с этой фамилией знакомы?

**Comment by emodaditz** [comment]
@bzaar  К нам на работу как раз один из них устроился. Все документы пришлось в ручную корректировать в части фамилии.

**Comment by bzaar** [comment]
А соискатель случайно не произносил свою фамилию? Куда в ней падает ударение?

**Comment by emodaditz** [comment]
@bzaar Узнали - на "И".

**Comment by bzaar** [comment]
@emodaditz  Большое спасибо!

**Comment by bzaar** [comment]
Ошибка исправлена - спасибо, что о ней сообщили!
